### ISSUE TITLE
ValueError: invalid literal for int() with base 10

### ISSUE THREAD

**Issue by ayangupt90** [Vikramank/Deep-Learning-#5]
Hello Vikramank...... Thanks for your useful code. When i run 1st cell of importing required packages i was get a warning based on **tflearn**: "curses is not supported on this machine (please install/reinstall curses for an optimal experience)". However after running 1st 4 cells i've not get any kind of error. But after running 5th cell i have got an error as follows. [I've googled for "ValueError: invalid literal for int() with base 10" but there have no support/result which help me for following problem][sorry to say that i'm using **HP 245 g5** laptop which have only 4GB RAM to run these codes] :
ValueError                                Traceback (most recent call last)
<ipython-input-5-6e91b1ffcc3d> in <module>()
      **_1 #Importing data
----> 2 X_train, Y_train = _image_pr_eloader(TRAIN_DATA, image_shape=(56,56),mode='file', categorical_labels=True,normalize=True)
      3 X_test, Y_test = image_preloader(TEST_DATA, image_shape=(56,56),mode='file', categorical_labels=True,normalize=True)
      4 X_val, Y_val = image_preloader(VALIDATION_DATA, image_shape=(56,56),mode='file', categorical_labels=True,normalize=True)_**

~\Anaconda3\lib\site-packages\tflearn-0.3.2-py3.6.egg\tflearn\data_utils.py in image_preloader(target_path, image_shape, mode, normalize, grayscale, categorical_labels, files_extension, filter_channel)
    537                             continue
    538                     images.append(l[0])
--> 539                     labels.append(int(l[1]))
    540 
    541     n_classes = np.max(labels) + 1

# ValueError: invalid literal for int() with base 10: 
'Gupta/Anaconda3/PROGRAM_TO_CLASSIFY_IMAGES/Dataset_for_Cats_Dogs/train/cat.11963.jpg''

**Comment by Vikramank** [comment]
Hi, 
What version of TensorFlow and TFlearn are you using?

**Comment by ayangupt90** [comment]
tflearn's version is 0.something.... That's mean i need to upgrade tflearn package ? Please specify that what version of Tensorflow as well as TFlearn are need to successfully run this code ..... !!
[Thanks for your response !!]

**Comment by ayangupt90** [comment]
Sorry to say that i can't get latest version of **tflearn** package (i.e. >=1). I've checked following website http://tflearn.org/installation/ & also tried to upgrade **tflearn** package. But it always says:
`Requirement already satisfied: tflearn in c:\users\ayan gupta\anaconda3\envs\project2\lib\site-packages (0.3.2)`

**Comment by ayangupt90** [comment]
tflearn's version & tensorflow's version are as follows (i'm trying to run it on Windows OS):
`tensorflow       1.8.0`
`tflearn          0.3.2`
When i'm trying to import packages following warnings are showing:
`hdf5 is not supported on this machine (please install/reinstall h5py for optimal experience)
curses is not supported on this machine (please install/reinstall curses for an optimal experience)
Scipy not supported!`

**Comment by Vikramank** [comment]
Hi, TFlearn uses h5 file format to perform some I/O operations. 
I would suggest to you the following.
1) Uninstall hdf5 and reinstall it
2) Try it in a Linux machine for avoiding errors like these

**Comment by ayangupt90** [comment]
Yea.. ! It works in Ubuntu OS. Except three warnings now its says only one warning as on Windows OS:
`hdf5 is not supported on this machine (please install/reinstall h5py for optimal experience)`
But until now i still not understood that why these errors occur in windows OS ... ! ! 
Anyway unfortunately there have one new problem arrived ! As it is a new problem it has been described as new issue..
Thanks for your effort to understanding my problem...

**Comment by ayangupt90** [comment]
Again new issue.... Please see GitHub for more details.....
Thank you...!!

**Comment by Vikramank** [comment]
Hi, this is strange. I've answered your querry in the relevant page
